---
-
  hosts: all
  gather_facts: true # this will make not to gather facts before running tasks

  tasks: 
    - name: stop service
      win_service:
        Name: {{ var_files }}
        state: stopped
      when: state == "started"

  vars_files:
    - services.yml

# you can also use
# loop:
#    - {name: 'Dinesh' , company: 'Generalmills'} You can call this by item.name and item.company 

...


# use same looping to stop the BITS and dhcp service



 

